name: Hello world
description: None
inputs:
  who-to-greet:
    required: true
    default: world
outputs:
  time:
    description: The time we said hello.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
