name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  another-job:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: 'Kasia'
  something-that-prints-output:
    runs-on: ubuntu-latest
    needs: [another-job]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
