name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  another-job:
    runs-on: ubuntu-latest
    steps:
    - name: trigger reusable job
      id: step1
      uses: ./.github/workflows/reusable.yml
      with:
        who-to-greet: 'Kasia'
    - run: echo "Time was ${{ step1.outputs.current-time }}"

  something-that-prints-output:
    runs-on: ubuntu-latest
    needs: [another-job]
    steps:
      - run: echo "Time was ${{ needs.another-job.outputs.current-time }}"
