name: Run designite java Action
on: [workflow_dispatch]

jobs:
  RunJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run action
        uses: ./testGitHubActions
